// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
// 
// Code generated by Microsoft (R) AutoRest Code Generator 0.11.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.


package fixtures.bodyarray;

import com.microsoft.rest.ServiceException;
import retrofit.Callback;
import retrofit.client.Response;

public interface arrayOperations {
    @GET("/array/null")
    Array getNull();

    @GET("/array/null")
    void getNullAsync(Callback<Response> cb);

    @GET("/array/invalid")
    Array getInvalid();

    @GET("/array/invalid")
    void getInvalidAsync(Callback<Response> cb);

    @GET("/array/empty")
    Array getEmpty();

    @GET("/array/empty")
    void getEmptyAsync(Callback<Response> cb);

    @PUT("/array/empty")
     putEmpty(Array arrayBody);

    @PUT("/array/empty")
    void putEmptyAsync(Array arrayBody, Callback<Response> cb);

    @GET("/array/prim/boolean/tfft")
    Array getBooleanTfft();

    @GET("/array/prim/boolean/tfft")
    void getBooleanTfftAsync(Callback<Response> cb);

    @PUT("/array/prim/boolean/tfft")
     putBooleanTfft(Array arrayBody);

    @PUT("/array/prim/boolean/tfft")
    void putBooleanTfftAsync(Array arrayBody, Callback<Response> cb);

    @GET("/array/prim/boolean/true.null.false")
    Array getBooleanInvalidNull();

    @GET("/array/prim/boolean/true.null.false")
    void getBooleanInvalidNullAsync(Callback<Response> cb);

    @GET("/array/prim/boolean/true.boolean.false")
    Array getBooleanInvalidString();

    @GET("/array/prim/boolean/true.boolean.false")
    void getBooleanInvalidStringAsync(Callback<Response> cb);

    @GET("/array/prim/integer/1.-1.3.300")
    Array getIntegerValid();

    @GET("/array/prim/integer/1.-1.3.300")
    void getIntegerValidAsync(Callback<Response> cb);

    @PUT("/array/prim/integer/1.-1.3.300")
     putIntegerValid(Array arrayBody);

    @PUT("/array/prim/integer/1.-1.3.300")
    void putIntegerValidAsync(Array arrayBody, Callback<Response> cb);

    @GET("/array/prim/integer/1.null.zero")
    Array getIntInvalidNull();

    @GET("/array/prim/integer/1.null.zero")
    void getIntInvalidNullAsync(Callback<Response> cb);

    @GET("/array/prim/integer/1.integer.0")
    Array getIntInvalidString();

    @GET("/array/prim/integer/1.integer.0")
    void getIntInvalidStringAsync(Callback<Response> cb);

    @GET("/array/prim/long/1.-1.3.300")
    Array getLongValid();

    @GET("/array/prim/long/1.-1.3.300")
    void getLongValidAsync(Callback<Response> cb);

    @PUT("/array/prim/long/1.-1.3.300")
     putLongValid(Array arrayBody);

    @PUT("/array/prim/long/1.-1.3.300")
    void putLongValidAsync(Array arrayBody, Callback<Response> cb);

    @GET("/array/prim/long/1.null.zero")
    Array getLongInvalidNull();

    @GET("/array/prim/long/1.null.zero")
    void getLongInvalidNullAsync(Callback<Response> cb);

    @GET("/array/prim/long/1.integer.0")
    Array getLongInvalidString();

    @GET("/array/prim/long/1.integer.0")
    void getLongInvalidStringAsync(Callback<Response> cb);

    @GET("/array/prim/float/0--0.01-1.2e20")
    Array getFloatValid();

    @GET("/array/prim/float/0--0.01-1.2e20")
    void getFloatValidAsync(Callback<Response> cb);

    @PUT("/array/prim/float/0--0.01-1.2e20")
     putFloatValid(Array arrayBody);

    @PUT("/array/prim/float/0--0.01-1.2e20")
    void putFloatValidAsync(Array arrayBody, Callback<Response> cb);

    @GET("/array/prim/float/0.0-null-1.2e20")
    Array getFloatInvalidNull();

    @GET("/array/prim/float/0.0-null-1.2e20")
    void getFloatInvalidNullAsync(Callback<Response> cb);

    @GET("/array/prim/float/1.number.0")
    Array getFloatInvalidString();

    @GET("/array/prim/float/1.number.0")
    void getFloatInvalidStringAsync(Callback<Response> cb);

    @GET("/array/prim/double/0--0.01-1.2e20")
    Array getDoubleValid();

    @GET("/array/prim/double/0--0.01-1.2e20")
    void getDoubleValidAsync(Callback<Response> cb);

    @PUT("/array/prim/double/0--0.01-1.2e20")
     putDoubleValid(Array arrayBody);

    @PUT("/array/prim/double/0--0.01-1.2e20")
    void putDoubleValidAsync(Array arrayBody, Callback<Response> cb);

    @GET("/array/prim/double/0.0-null-1.2e20")
    Array getDoubleInvalidNull();

    @GET("/array/prim/double/0.0-null-1.2e20")
    void getDoubleInvalidNullAsync(Callback<Response> cb);

    @GET("/array/prim/double/1.number.0")
    Array getDoubleInvalidString();

    @GET("/array/prim/double/1.number.0")
    void getDoubleInvalidStringAsync(Callback<Response> cb);

    @GET("/array/prim/string/foo1.foo2.foo3")
    Array getStringValid();

    @GET("/array/prim/string/foo1.foo2.foo3")
    void getStringValidAsync(Callback<Response> cb);

    @PUT("/array/prim/string/foo1.foo2.foo3")
     putStringValid(Array arrayBody);

    @PUT("/array/prim/string/foo1.foo2.foo3")
    void putStringValidAsync(Array arrayBody, Callback<Response> cb);

    @GET("/array/prim/string/foo.null.foo2")
    Array getStringWithNull();

    @GET("/array/prim/string/foo.null.foo2")
    void getStringWithNullAsync(Callback<Response> cb);

    @GET("/array/prim/string/foo.123.foo2")
    Array getStringWithInvalid();

    @GET("/array/prim/string/foo.123.foo2")
    void getStringWithInvalidAsync(Callback<Response> cb);

    @GET("/array/prim/date/valid")
    Array getDateValid();

    @GET("/array/prim/date/valid")
    void getDateValidAsync(Callback<Response> cb);

    @PUT("/array/prim/date/valid")
     putDateValid(Array arrayBody);

    @PUT("/array/prim/date/valid")
    void putDateValidAsync(Array arrayBody, Callback<Response> cb);

    @GET("/array/prim/date/invalidnull")
    Array getDateInvalidNull();

    @GET("/array/prim/date/invalidnull")
    void getDateInvalidNullAsync(Callback<Response> cb);

    @GET("/array/prim/date/invalidchars")
    Array getDateInvalidChars();

    @GET("/array/prim/date/invalidchars")
    void getDateInvalidCharsAsync(Callback<Response> cb);

    @GET("/array/prim/date-time/valid")
    Array getDateTimeValid();

    @GET("/array/prim/date-time/valid")
    void getDateTimeValidAsync(Callback<Response> cb);

    @PUT("/array/prim/date-time/valid")
     putDateTimeValid(Array arrayBody);

    @PUT("/array/prim/date-time/valid")
    void putDateTimeValidAsync(Array arrayBody, Callback<Response> cb);

    @GET("/array/prim/date-time/invalidnull")
    Array getDateTimeInvalidNull();

    @GET("/array/prim/date-time/invalidnull")
    void getDateTimeInvalidNullAsync(Callback<Response> cb);

    @GET("/array/prim/date-time/invalidchars")
    Array getDateTimeInvalidChars();

    @GET("/array/prim/date-time/invalidchars")
    void getDateTimeInvalidCharsAsync(Callback<Response> cb);

    @GET("/array/prim/byte/valid")
    Array getByteValid();

    @GET("/array/prim/byte/valid")
    void getByteValidAsync(Callback<Response> cb);

    @PUT("/array/prim/byte/valid")
     putByteValid(Array arrayBody);

    @PUT("/array/prim/byte/valid")
    void putByteValidAsync(Array arrayBody, Callback<Response> cb);

    @GET("/array/prim/byte/invalidnull")
    Array getByteInvalidNull();

    @GET("/array/prim/byte/invalidnull")
    void getByteInvalidNullAsync(Callback<Response> cb);

    @GET("/array/complex/null")
    Array getComplexNull();

    @GET("/array/complex/null")
    void getComplexNullAsync(Callback<Response> cb);

    @GET("/array/complex/empty")
    Array getComplexEmpty();

    @GET("/array/complex/empty")
    void getComplexEmptyAsync(Callback<Response> cb);

    @GET("/array/complex/itemnull")
    Array getComplexItemNull();

    @GET("/array/complex/itemnull")
    void getComplexItemNullAsync(Callback<Response> cb);

    @GET("/array/complex/itemempty")
    Array getComplexItemEmpty();

    @GET("/array/complex/itemempty")
    void getComplexItemEmptyAsync(Callback<Response> cb);

    @GET("/array/complex/valid")
    Array getComplexValid();

    @GET("/array/complex/valid")
    void getComplexValidAsync(Callback<Response> cb);

    @PUT("/array/complex/valid")
     putComplexValid(Array arrayBody);

    @PUT("/array/complex/valid")
    void putComplexValidAsync(Array arrayBody, Callback<Response> cb);

    @GET("/array/array/null")
    Array getArrayNull();

    @GET("/array/array/null")
    void getArrayNullAsync(Callback<Response> cb);

    @GET("/array/array/empty")
    Array getArrayEmpty();

    @GET("/array/array/empty")
    void getArrayEmptyAsync(Callback<Response> cb);

    @GET("/array/array/itemnull")
    Array getArrayItemNull();

    @GET("/array/array/itemnull")
    void getArrayItemNullAsync(Callback<Response> cb);

    @GET("/array/array/itemempty")
    Array getArrayItemEmpty();

    @GET("/array/array/itemempty")
    void getArrayItemEmptyAsync(Callback<Response> cb);

    @GET("/array/array/valid")
    Array getArrayValid();

    @GET("/array/array/valid")
    void getArrayValidAsync(Callback<Response> cb);

    @PUT("/array/array/valid")
     putArrayValid(Array arrayBody);

    @PUT("/array/array/valid")
    void putArrayValidAsync(Array arrayBody, Callback<Response> cb);

    @GET("/array/dictionary/null")
    Array getDictionaryNull();

    @GET("/array/dictionary/null")
    void getDictionaryNullAsync(Callback<Response> cb);

    @GET("/array/dictionary/empty")
    Array getDictionaryEmpty();

    @GET("/array/dictionary/empty")
    void getDictionaryEmptyAsync(Callback<Response> cb);

    @GET("/array/dictionary/itemnull")
    Array getDictionaryItemNull();

    @GET("/array/dictionary/itemnull")
    void getDictionaryItemNullAsync(Callback<Response> cb);

    @GET("/array/dictionary/itemempty")
    Array getDictionaryItemEmpty();

    @GET("/array/dictionary/itemempty")
    void getDictionaryItemEmptyAsync(Callback<Response> cb);

    @GET("/array/dictionary/valid")
    Array getDictionaryValid();

    @GET("/array/dictionary/valid")
    void getDictionaryValidAsync(Callback<Response> cb);

    @PUT("/array/dictionary/valid")
     putDictionaryValid(Array arrayBody);

    @PUT("/array/dictionary/valid")
    void putDictionaryValidAsync(Array arrayBody, Callback<Response> cb);

}
