group: deprecated-2017Q3
language: csharp
sudo: required
dist: trusty
addons:
  apt:
    sources:
    - deadsnakes
    packages:
    # packages for python
    - python3.5
env:
  matrix:
  - MODE=main
matrix:
  fast_finish: true
  allow_failures:
    - env: MODE=diffRegenSpecsRepo
before_install:
  # Attempt to work around fact that node modules mess up rvm
  - PATH=`echo $PATH | sed "s/\.\/node_modules\/\.bin//g"`
  - export PATH=$PATH:./node_modules/.bin
install:
    # Install npm
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install 7.10.0
  - npm install -g npm@'>=5.0.4'
  - npm install
script:
  - set -e
  - set -o pipefail
  - gulp build
  - gulp test
after_script:
  - |-
    echo "========== Server log: ============"
    pwd
    ls -al
    ls -al TestResults
    cat TestResults/*.log
notifications:
  slack:
    secure: d0PFVLcyqcMxNtmZ8JaEpIBzXbUbZCgKs8QtBB5qEIXDnxflSR3AhczlILNhTBKtMEBlwVzsz65yP09XcmvB6xpAfJbHqSRzk2frKa5viPcAD8Wr/NYamt9/UiTCsnql8MqzjVy0tLdMscXKRmsUey4YF570zl0b7gAbq7XTqxM=
