/*
 * Code generated by Microsoft (R) AutoRest Code Generator 1.2.0.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Class representing a StorageAccountRegenerateKeyParameters.
 */
class StorageAccountRegenerateKeyParameters {
  /**
   * Create a StorageAccountRegenerateKeyParameters.
   * @member {string} keyName
   */
  constructor() {
  }

  /**
   * Defines the metadata of StorageAccountRegenerateKeyParameters
   *
   * @returns {object} metadata of StorageAccountRegenerateKeyParameters
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'StorageAccountRegenerateKeyParameters',
      type: {
        name: 'Composite',
        className: 'StorageAccountRegenerateKeyParameters',
        modelProperties: {
          keyName: {
            required: true,
            serializedName: 'keyName',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = StorageAccountRegenerateKeyParameters;
