// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.
//
// To add a suppression to this file, right-click the message in the
// Code Analysis results, point to "Suppress Message", and click
// "In Suppression File".
// You do not need to add suppressions to this file manually.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity", Scope = "member", Target = "AutoRest.CSharp.Tests.TestExtensions.#ToStatusCode(System.String)", Justification = "False Positive")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1505:AvoidUnmaintainableCode", Scope = "member", Target = "AutoRest.CSharp.Tests.AcceptanceTests.#ArrayTests()", Justification = "False Positive")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1505:AvoidUnmaintainableCode", Scope = "member", Target = "AutoRest.CSharp.Tests.AcceptanceTests.#DictionaryTests()", Justification = "False Positive")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1505:AvoidUnmaintainableCode", Scope = "member", Target = "AutoRest.CSharp.Tests.AcceptanceTests.#ComplexTests()", Justification = "False Positive")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1505:AvoidUnmaintainableCode", Scope = "member", Target = "AutoRest.CSharp.Tests.AcceptanceTests.#HttpInfrastructureTests()", Justification = "False Positive")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1809:AvoidExcessiveLocals", Scope = "member", Target = "AutoRest.CSharp.Tests.AcceptanceTests.#ArrayTests()", Justification = "Fixture values for serialization")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1809:AvoidExcessiveLocals", Scope = "member", Target = "AutoRest.CSharp.Tests.AcceptanceTests.#DictionaryTests()", Justification = "Fixture values for serialization")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1809:AvoidExcessiveLocals", Scope = "member", Target = "AutoRest.CSharp.Tests.AcceptanceTests.#ComplexTests()", Justification = "Fixture values for serialization")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2208:InstantiateArgumentExceptionsCorrectly", Scope = "member", Target = "Fixtures.AcceptanceTestsRequiredOptional.Models.ArrayWrapper.#Validate()", Justification="Validation exceptions types are being changed")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2208:InstantiateArgumentExceptionsCorrectly", Scope = "member", Target = "Fixtures.AcceptanceTestsRequiredOptional.Models.ClassWrapper.#Validate()", Justification="Validation exceptions types are being changed")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2208:InstantiateArgumentExceptionsCorrectly", Scope = "member", Target = "Fixtures.MirrorSequences.Models.ErrorModel.#Validate()", Justification="Validation exceptions types are being changed")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2208:InstantiateArgumentExceptionsCorrectly", Scope = "member", Target = "Fixtures.AcceptanceTestsBodyComplex.Models.Fish.#Validate()", Justification="Validation exceptions types are being changed")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2208:InstantiateArgumentExceptionsCorrectly", Scope = "member", Target = "Fixtures.AcceptanceTestsRequiredOptional.Models.IntWrapper.#Validate()", Justification="Validation exceptions types are being changed")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2208:InstantiateArgumentExceptionsCorrectly", Scope = "member", Target = "Fixtures.MirrorSequences.Models.Pet.#Validate()", Justification="Validation exceptions types are being changed")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2208:InstantiateArgumentExceptionsCorrectly", Scope = "member", Target = "Fixtures.PetstoreV2.Models.Pet.#Validate()", Justification="Validation exceptions types are being changed")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2208:InstantiateArgumentExceptionsCorrectly", Scope = "member", Target = "Fixtures.MirrorSequences.Models.PetStyle.#Validate()", Justification="Validation exceptions types are being changed")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2208:InstantiateArgumentExceptionsCorrectly", Scope = "member", Target = "Fixtures.AcceptanceTestsRequiredOptional.Models.Product.#Validate()", Justification="Validation exceptions types are being changed")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2208:InstantiateArgumentExceptionsCorrectly", Scope = "member", Target = "Fixtures.AcceptanceTestsBodyComplex.Models.Shark.#Validate()", Justification="Validation exceptions types are being changed")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2208:InstantiateArgumentExceptionsCorrectly", Scope = "member", Target = "Fixtures.AcceptanceTestsRequiredOptional.Models.StringWrapper.#Validate()", Justification="Validation exceptions types are being changed")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:Dispose objects before losing scope", Scope = "member", Target = "AutoRest.CSharp.Tests.ServiceController.#StartServiceProcess(System.String,System.String,System.String,System.Boolean)", Justification="Service process cannot be disposed at method end")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:Dispose objects before losing scope", Scope = "member", Target = "AutoRest.CSharp.Tests.MirrorTestHelpers.#CreateDataClient()", Justification = "Handler cannot be disposed at method end")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:Dispose objects before losing scope", Scope = "member", Target = "AutoRest.CSharp.Tests.MirrorTests.#UrlIsCorrectWhenBaseUriContainsSegment()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "npm", Scope = "member", Target = "AutoRest.CSharp.Tests.ServiceController.#StartServiceProcess()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1057:StringUriOverloadsCallSystemUriOverloads", Scope = "member", Target = "Fixtures.AcceptanceTestsUrl.AutoRestUrlTestService.#.ctor(System.String,System.Net.Http.DelegatingHandler[])", Justification = "Invalid in the current context.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1809:AvoidExcessiveLocals", Scope = "member", Target = "AutoRest.CSharp.Tests.AcceptanceTests.#TestDictionaryPrimitiveTypes(Fixtures.AcceptanceTestsBodyDictionary.AutoRestSwaggerBATdictionaryService)")]
