// Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ApplicationGateway.Models
{

    /// <summary>
    /// Defines values for IPVersion.
    /// </summary>
    public static class IPVersion
    {
        public const string IPv4 = "IPv4";
        public const string IPv6 = "IPv6";
    }
}
