source 'https://rubygems.org'

group :development, :local, :test do
  gem 'rspec'
  gem 'ms_rest', path:'../../../../ClientRuntimes/Ruby/ms-rest'
  gem 'ms_rest_azure', path:'../../../../ClientRuntimes/Ruby/ms-rest-azure'
end
