// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.
//
// To add a suppression to this file, right-click the message in the
// Code Analysis results, point to "Suppress Message", and click
// "In Suppression File".
// You do not need to add suppressions to this file manually.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope = "namespace", Target = "Microsoft.Rest.Generator.Azure.Ruby.Templates")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "Microsoft.Rest.Generator.Utilities.IndentedStringBuilder.AppendLine(System.String)", Scope = "member", Target = "Microsoft.Rest.Generator.Azure.Ruby.AzureMethodTemplateModel.#BuildUrl(System.String,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "subscriptionid", Scope = "member", Target = "Microsoft.Rest.Generator.Azure.Ruby.AzureMethodTemplateModel.#BuildUrl(System.String,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", MessageId = "isRequired", Scope = "member", Target = "Microsoft.Rest.Generator.Azure.Ruby.AzureMethodTemplateModel.#DeserializePollingResponse(System.String,Microsoft.Rest.Generator.ClientModel.IType,System.Boolean,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "httprequest", Scope = "member", Target = "Microsoft.Rest.Generator.Azure.Ruby.AzureMethodTemplateModel.#SetDefaultHeaders")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "uuid", Scope = "member", Target = "Microsoft.Rest.Generator.Azure.Ruby.AzureMethodTemplateModel.#SetDefaultHeaders")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "SecureRandom", Scope = "member", Target = "Microsoft.Rest.Generator.Azure.Ruby.AzureMethodTemplateModel.#SetDefaultHeaders")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "Microsoft.Rest.Generator.Utilities.IndentedStringBuilder.AppendLine(System.String)", Scope = "member", Target = "Microsoft.Rest.Generator.Azure.Ruby.AzureMethodTemplateModel.#SetDefaultHeaders")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "statuscode", Scope = "member", Target = "Microsoft.Rest.Generator.Azure.Ruby.AzureMethodTemplateModel.#InitializeResponseBody")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "Microsoft.Rest.Generator.Utilities.IndentedStringBuilder.AppendLine(System.String)", Scope = "member", Target = "Microsoft.Rest.Generator.Azure.Ruby.AzureMethodTemplateModel.#InitializeResponseBody")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "requestid", Scope = "member", Target = "Microsoft.Rest.Generator.Azure.Ruby.AzureMethodTemplateModel.#InitializeResponseBody")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "httpresponse", Scope = "member", Target = "Microsoft.Rest.Generator.Azure.Ruby.AzureMethodTemplateModel.#InitializeResponseBody")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "Util", Scope = "member", Target = "Microsoft.Rest.Generator.Azure.Ruby.AzureMethodTemplateModel.#BuildUrl(System.String,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "urlencode", Scope = "member", Target = "Microsoft.Rest.Generator.Azure.Ruby.AzureMethodTemplateModel.#BuildUrl(System.String,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "requestheaders", Scope = "member", Target = "Microsoft.Rest.Generator.Azure.Ruby.AzureMethodTemplateModel.#SetDefaultHeaders")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists", Scope = "member", Target = "Microsoft.Rest.Generator.Azure.Ruby.AzureMethodTemplateModel.#FaradeyMiddlewares")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists", Scope = "member", Target = "Microsoft.Rest.Generator.Azure.Ruby.AzureMethodGroupTemplateModel.#Includes")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists", Scope = "member", Target = "Microsoft.Rest.Generator.Azure.Ruby.AzureModelTemplateModel.#Includes")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists", Scope = "member", Target = "Microsoft.Rest.Generator.Azure.Ruby.AzureServiceClientTemplateModel.#Includes")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Microsoft.Rest.Generator.Azure.Ruby.AzureRequirementsTemplateModel.#ExcludeModel(Microsoft.Rest.Generator.ClientModel.CompositeType)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Microsoft.Rest.Generator.Azure.Ruby.AzureRubyCodeGenerator.#CorrectFilterParameters(Microsoft.Rest.Generator.ClientModel.ServiceClient)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists", Scope = "member", Target = "Microsoft.Rest.Generator.Azure.Ruby.AzureMethodTemplateModel.#ClassNamespaces")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists", Scope = "member", Target = "Microsoft.Rest.Generator.Azure.Ruby.AzureModelTemplateModel.#ClassNamespaces")]
