# encoding: utf-8
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.

source 'https://rubygems.org'

# Specify your gem's dependencies in ms_rest_azure.gemspec
gemspec

group :development do
  gem 'ms_rest', path: '../ms-rest'
end

group :test do
  gem 'rspec'
end