# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - master

pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: main
    displayName: Main
    jobs:
      - job: main
        displayName: "Build and Unit test"
        steps:
          - ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
              - template: ./templates/verify-changes.yaml

          - template: ./templates/build.yaml

          - script: npx @microsoft/rush test:ci -v
            displayName: Test

          - task: PublishCodeCoverageResults@1
            inputs:
              codeCoverageTool: Cobertura
              summaryFileLocation: $(Build.SourcesDirectory)/packages/**/coverage/cobertura-coverage.xml
              reportDirectory: $(Build.SourcesDirectory)/packages/**/coverage

          - script: npx @microsoft/rush lint -v
            displayName: Lint

          - script: |
              commitId=$(git rev-parse --short HEAD)
              npx @microsoft/rush publish --apply --prerelease-name="ci.$commitId"
            displayName: Bump versions

          - script: npx @microsoft/rush publish --publish --pack --include-all
            displayName: Pack packages

          - publish: $(Build.SourcesDirectory)/common/temp/artifacts/packages
            artifact: packages
            displayName: Publish packages(.tgz) as pipeline artifacts

          - ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
              - template: ./templates/create-tryit-comment.yaml
      - job: lintdocs
        displayName: Lint docs
        steps:
          - script: |
              sudo npm install -g markdown-link-check
              find docs -name "*.md" -print0 | xargs -0  -n1 markdown-link-check -c ./markdown-link-check-config.json
            displayName: Find
  - stage: regressiontests
    displayName: Regression Tests
    dependsOn: main
    jobs:
      - template: ./templates/regression-tests.yaml
        parameters:
          name: node10
          nodeVersion: 10.x
      - template: ./templates/regression-tests.yaml
        parameters:
          name: node12
          nodeVersion: 12.x
      - template: ./templates/regression-tests.yaml
        parameters:
          name: node14
          nodeVersion: 14.x
      - template: ./templates/regression-tests.yaml
        parameters:
          name: node16
          nodeVersion: 16.x

  - stage: smoketests
    displayName: Smoke Tests
    dependsOn: main
    jobs:
      - template: ./templates/smoke-tests.yaml
        parameters:
          name: node14
          nodeVersion: 14.x
