# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger: none

pool:
  vmImage: "ubuntu-latest"

jobs:
  - job: main
    displayName: "Build and test"
    steps:
      - template: ./templates/verify-changes.yaml
      - template: ./templates/build.yaml

      # - script: npx @microsoft/rush test:ci -v
      #   displayName: Test

      # - script: npx @microsoft/rush lint -v
      #   displayName: Lint

      - script: npx @microsoft/rush publish --publish --pack --include-all
        displayName: Pack packages

      - script: ls $(Build.SourcesDirectory)/common/temp/artifacts/packages

      - publish: $(Build.SourcesDirectory)/common/temp/artifacts/packages
        artifact: packages

      # - template: ./templates/create-tryit-comment.yaml

  - job: regressiontests
    displayName: Regression tests
    dependsOn: main
    steps:
      - download: current
        artifact: packages

      - script: ls ./packages
      - script: |
          corePkg="$(find ./packages -type f -iname "autorest-core-*.tgz" )"
          modelerfourPkg="$(find ./packages -type f -iname "autorest-modelerfour-*.tgz" )"

          echo "Found core package $corePkg"
          echo "Found modelerfour package $modelerfourPkg"

          sed -i "s,--version:../packages/extensions/core,$corePkg," ./.script/regression-compare.yaml
          sed -i "s,--version:../packages/extensions/modelerfour,$modelerfourPkg," ./.script/regression-compare.yaml
        displayName: Find packages path

      - script: cat ./.script/regression-compare.yaml

      - task: NodeTool@0
        inputs:
          versionSpec: "14.x"
        displayName: "Install Node.js"

      - task: UsePythonVersion@0
        inputs:
          versionSpec: "3.x"
        displayName: Install Python 3

      - script: |
          npm install @microsoft.azure/autorest.testserver --no-save
          npm install -g @autorest/compare@~0.3.0
        displayName: Install autorest-compare

      - script: autorest-compare --compare:.scripts/regression-compare.yaml --language:python
        displayName: Regression Test - @autorest/python

      - script: autorest-compare --compare:.scripts/regression-compare.yaml --language:typescript
        displayName: Regression Test - @autorest/typescript

  - job: lintdocs
    displayName: Lint docs
    steps:
      - script: |
          sudo npm install -g markdown-link-check
          find docs -name "*.md" -print0 | xargs -0  -n1 markdown-link-check -c ./markdown-link-check-config.json
        displayName: Find
