# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - master

pool:
  vmImage: "ubuntu-latest"
jobs:
  # - job: stable
  #   displayName: Publish stable
  #   steps:
  #     - template: ./templates/build.yaml

  #     - script: npx @microsoft/rush publish --publish --pack --include-all
  #       displayName: Pack packages

  #     - script: |
  #         NPM_AUTH_TOKEN="$(azure-sdk-npm-token)" npx @microsoft/rush publish --publish --include-all --set-access-level public
  #       displayName: Publish packages

  # - job: prerelease
  #   displayName: Publish prerelease
  #   dependsOn: stable # Publish prerelease after to prevent race condition.
  #   steps:
  #     - template: ./templates/build.yaml

  #     - script: node ./eng/bump-for-prerelease.js
  #       displayName: Bump version to prerelease targets

  #     - script: |
  #         NPM_AUTH_TOKEN="$(azure-sdk-npm-token)" npx @microsoft/rush publish --publish --include-all --set-access-level public --tag next
  #       displayName: Publish packages
  - job: docker
    displayName: Publish to docker
    steps:
      - task: DockerInstaller@0
        inputs:
          dockerVersion: "17.09.0-ce"

      - script: |
          echo "$(DockerHub-azuresdkPass)" | docker login -u "azuresdk" --password-stdin
        displayName: Login to docker hub.

      - script: |
          docker build -t azuresdk/autorest .
        displayName: Build image
        workingDirectory: ./docker/base/ubuntu

      - script: |
          docker push azuresdk/autorest
        displayName: Publish image

      - script: |
          docker run -v $PWD/docker:/worksdpace \
            -e DOCKERHUB_USERNAME="azuresdk" \
            -e DOCKERHUB_PASSWORD="$(DockerHub-azuresdkPass)" \
            -e DOCKERHUB_REPOSITORY='azuresdk/autorest' \
            -e README_FILEPATH='/worksdpace/base/readme.md' \
            peterevans/dockerhub-description:2.1.0
        displayName: Update readme
