swagger: '2.0'
info:
  version: 1.0.0
  title: Simple API
paths:
  /operation:
    get:
      operationId: operation1
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/ResultObject'

definitions:
  ResultObject:
    properties:
      Message:
        type: string
        description: 'This is a response.'
