swagger: '2.0'
info:
  version: 1.0.0
  title: Simple API
paths:
  /operation:
    get:
      operationId: test
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/ResultObject'

definitions: 
  ResultObject:
    required: [
      MemberInt100,
      MemberInt110]
    properties:
      MemberInt000:
        type: integer
        readOnly: false
      MemberInt001:
        type: integer
        readOnly: true
      MemberInt010:
        type: integer
        readOnly: false
        default: 42
      MemberInt011:
        type: integer
        readOnly: true
        default: 42
      MemberInt100:
        type: integer
        readOnly: false
      MemberInt110:
        type: integer
        readOnly: false
        default: 42
