/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

const models = require('./index');

/**
 * Class representing a CatalogDictionary.
 */
class CatalogDictionary {
  /**
   * Create a CatalogDictionary.
   * @member {object} [productDictionary] Dictionary of products
   */
  constructor() {
  }

  /**
   * Defines the metadata of CatalogDictionary
   *
   * @returns {object} metadata of CatalogDictionary
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'CatalogDictionary',
      type: {
        name: 'Composite',
        className: 'CatalogDictionary',
        modelProperties: {
          productDictionary: {
            required: false,
            serializedName: 'productDictionary',
            type: {
              name: 'Dictionary',
              value: {
                  required: false,
                  serializedName: 'ProductElementType',
                  type: {
                    name: 'Composite',
                    className: 'Product'
                  }
              }
            }
          }
        }
      }
    };
  }
}

module.exports = CatalogDictionary;
