// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.
//
// To add a suppression to this file, right-click the message in the 
// Code Analysis results, point to "Suppress Message", and click 
// "In Suppression File".
// You do not need to add suppressions to this file manually.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity", Scope = "member", Target = "Microsoft.Rest.Generator.CSharp.Tests.TestExtensions.#ToStatusCode(System.String)", Justification = "False Positive")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1505:AvoidUnmaintainableCode", Scope = "member", Target = "Microsoft.Rest.Generator.CSharp.Tests.CSharpSwaggerBat.#ArrayTests()", Justification = "False Positive")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1505:AvoidUnmaintainableCode", Scope = "member", Target = "Microsoft.Rest.Generator.CSharp.Tests.CSharpSwaggerBat.#DictionaryTests()", Justification = "False Positive")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1505:AvoidUnmaintainableCode", Scope = "member", Target = "Microsoft.Rest.Generator.CSharp.Tests.CSharpSwaggerBat.#ComplexTests()", Justification = "False Positive")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1505:AvoidUnmaintainableCode", Scope = "member", Target = "Microsoft.Rest.Generator.CSharp.Tests.CSharpSwaggerBat.#HttpInfrastructureTests()", Justification = "False Positive")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1809:AvoidExcessiveLocals", Scope = "member", Target = "Microsoft.Rest.Generator.CSharp.Tests.CSharpSwaggerBat.#ArrayTests()", Justification = "Fixture values for serialization")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1809:AvoidExcessiveLocals", Scope = "member", Target = "Microsoft.Rest.Generator.CSharp.Tests.CSharpSwaggerBat.#DictionaryTests()", Justification = "Fixture values for serialization")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1809:AvoidExcessiveLocals", Scope = "member", Target = "Microsoft.Rest.Generator.CSharp.Tests.CSharpSwaggerBat.#ComplexTests()", Justification = "Fixture values for serialization")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "Microsoft.Rest.Generator.CSharp.Tests.CSharpCodeNamingFrameworkTests.#TypeNormalizationTest()", Justification = "Test classes must be non-static to allow fixtures")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "Microsoft.Rest.Generator.CSharp.Tests.CSharpCodeNamingFrameworkTests.#TypeNormalizationWithComplexTypesTest()", Justification = "Test classes must be non-static to allow fixtures")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "Microsoft.Rest.Generator.CSharp.Tests.CSharpCodeNamingFrameworkTests.#VerifyMethodRenaming()", Justification = "Test classes must be non-static to allow fixtures")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "Microsoft.Rest.Generator.CSharp.Tests.CSharpCodeNamingFrameworkTests.#NameCollisionTestWithoutNamespace()", Justification = "Test classes must be non-static to allow fixtures")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "Microsoft.Rest.Generator.CSharp.Tests.CSharpCodeNamingFrameworkTests.#NameCollisionTestWithNamespace()", Justification = "Test classes must be non-static to allow fixtures")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "Microsoft.Rest.Generator.CSharp.Tests.CSharpCodeNamingFrameworkTests.#SequenceWithRenamedComplexType()", Justification = "Test classes must be non-static to allow fixtures")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "Microsoft.Rest.Generator.CSharp.Tests.CSharpSwaggerBat.#EnsureStatusCode`1(System.Net.HttpStatusCode,System.Func`1<System.Threading.Tasks.Task`1<Microsoft.Rest.HttpOperationResponse`1<!!0>>>)", Justification = "Test classes must be non-static to allow fixtures")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "Microsoft.Rest.Generator.CSharp.Tests.MirrorTests.#CanRoundTripSequences()", Justification = "Test classes must be non-static to allow fixtures")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "Microsoft.Rest.Generator.CSharp.Tests.MirrorTests.#CanRoundtripPolymorphicTypes()", Justification = "Test classes must be non-static to allow fixtures")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "Microsoft.Rest.Generator.CSharp.Tests.MirrorTests.#CanRoundtripFilledOutNestedTypesWithoutRecursion()", Justification = "Test classes must be non-static to allow fixtures")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "Microsoft.Rest.Generator.CSharp.Tests.MirrorTests.#CanRoundtripFilledOutNestedTypesWithoutRecursion2()", Justification = "Test classes must be non-static to allow fixtures")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "Microsoft.Rest.Generator.CSharp.Tests.ProcessOutputListener.#ScrubAndWriteValue(System.String,System.String)", Justification = "Test classes must be non-static to allow fixtures")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "Microsoft.Rest.Generator.CSharp.Tests.MirrorTests.#CanSerializeAndDeserializePrimitiveTypes()", Justification = "Test classes must be non-static to allow fixtures")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2208:InstantiateArgumentExceptionsCorrectly", Scope = "member", Target = "Fixtures.SwaggerBatRequiredOptional.Models.ArrayWrapper.#Validate()", Justification="Validation exceptions types are being changed")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2208:InstantiateArgumentExceptionsCorrectly", Scope = "member", Target = "Fixtures.SwaggerBatRequiredOptional.Models.ClassWrapper.#Validate()", Justification="Validation exceptions types are being changed")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2208:InstantiateArgumentExceptionsCorrectly", Scope = "member", Target = "Fixtures.MirrorSequences.Models.ErrorModel.#Validate()", Justification="Validation exceptions types are being changed")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2208:InstantiateArgumentExceptionsCorrectly", Scope = "member", Target = "Fixtures.SwaggerBatBodyComplex.Models.Fish.#Validate()", Justification="Validation exceptions types are being changed")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2208:InstantiateArgumentExceptionsCorrectly", Scope = "member", Target = "Fixtures.SwaggerBatRequiredOptional.Models.IntWrapper.#Validate()", Justification="Validation exceptions types are being changed")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2208:InstantiateArgumentExceptionsCorrectly", Scope = "member", Target = "Fixtures.MirrorSequences.Models.Pet.#Validate()", Justification="Validation exceptions types are being changed")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2208:InstantiateArgumentExceptionsCorrectly", Scope = "member", Target = "Fixtures.PetstoreV2.Models.Pet.#Validate()", Justification="Validation exceptions types are being changed")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2208:InstantiateArgumentExceptionsCorrectly", Scope = "member", Target = "Fixtures.MirrorSequences.Models.PetStyle.#Validate()", Justification="Validation exceptions types are being changed")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2208:InstantiateArgumentExceptionsCorrectly", Scope = "member", Target = "Fixtures.SwaggerBatRequiredOptional.Models.Product.#Validate()", Justification="Validation exceptions types are being changed")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2208:InstantiateArgumentExceptionsCorrectly", Scope = "member", Target = "Fixtures.SwaggerBatBodyComplex.Models.Shark.#Validate()", Justification="Validation exceptions types are being changed")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2208:InstantiateArgumentExceptionsCorrectly", Scope = "member", Target = "Fixtures.SwaggerBatRequiredOptional.Models.StringWrapper.#Validate()", Justification="Validation exceptions types are being changed")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:Dispose objects before losing scope", Scope = "member", Target = "Microsoft.Rest.Generator.CSharp.Tests.ServiceController.#StartServiceProcess(System.String,System.String,System.String,System.Boolean)", Justification="Service process cannot be disposed at method end")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "npm", Scope = "member", Target = "Microsoft.Rest.Generator.CSharp.Tests.ServiceController.#StartServiceProcess()")]
