---
swagger: '2.0'
info:
  title: PetStore Inc.
  description: Pets online.
  version: 0.0.0
consumes:
- application/json
produces:
- application/json
paths:
  "/Pets/{petId}/GetPet":
    post:
      operationId: Pet_GetPetById
      description: Gets pets by id.
      parameters:
      - name: petId
        in: path
        required: true
        type: string
        description: pet id
      responses:
        '200':
          description: ''
          schema:
            "$ref": "#/definitions/Pet"
        '202':
          description: ''
        '204':
          description: ''
        default:
          description: default stuff
definitions:
  Pet:
    properties:
      name:
        type: string
        readOnly: true
        description: Gets the Pet by id.
