#--------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
# 
# Code generated by Microsoft (R) AutoRest Code Generator 0.13.0.0
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
#--------------------------------------------------------------------------

import sys


from msrest.service_client import ServiceClient
from msrest.serialization import Serializer, Deserializer
from msrest.exceptions import (
    SerializationError,
    DeserializationError,
    TokenExpiredError,
    ClientRequestError,
    HttpOperationError)

from ..models import *

class DictionaryOperations(object):

    def __init__(self, client, config, serializer, derserializer):

        self._client = client
        self._serialize = serializer
        self._deserialize = derserializer

        self.config = config

    def _parse_url(self, name, value, datatype):

        try:
            value = self._serialize.serialize_data(value, str(datatype))

        except ValueError:
            raise ValueError("{} must not be None.".format(name))

        except DeserializationError:
            raise TypeError("{} must be type {}.".format(name, datatype))

        else:
            return value

    @ServiceClient.async_request
    def get_valid(self, custom_headers = {}, raw = False, callback = None):
        """

        Get complex types with dictionary property
        """

        # Construct URL
        url = '/complex/dictionary/typed/valid'

        # Construct parameters
        query = {}

        # Construct headers
        headers = {}
        headers.update(custom_headers)
        headers['Content-Type'] = 'application/json; charset=utf-8'

        # Construct and send request
        request = self._client.get(url, query)
        response = self._client.send(request, headers)

        if response.status_code not in [200]:
            raise ErrorException(self._deserialize, response)

        deserialized = None

        if response.status_code == 200:
            deserialized = self._deserialize('DictionaryWrapper', response)

        if raw:
            return deserialized, response

        return deserialized

    @ServiceClient.async_request
    def put_valid(self, complex_body, custom_headers = {}, raw = False, callback = None):
        """

        Put complex types with dictionary property
        """

        # Construct URL
        url = '/complex/dictionary/typed/valid'

        # Construct parameters
        query = {}

        # Construct headers
        headers = {}
        headers.update(custom_headers)
        headers['Content-Type'] = 'application/json; charset=utf-8'

        # Construct body
        content = self._serialize(complex_body, 'DictionaryWrapper')

        # Construct and send request
        request = self._client.put(url, query)
        response = self._client.send(request, headers, content)

        if response.status_code not in [200]:
            raise ErrorException(self._deserialize, response)

        if raw:
            return None, response

    @ServiceClient.async_request
    def get_empty(self, custom_headers = {}, raw = False, callback = None):
        """

        Get complex types with dictionary property which is empty
        """

        # Construct URL
        url = '/complex/dictionary/typed/empty'

        # Construct parameters
        query = {}

        # Construct headers
        headers = {}
        headers.update(custom_headers)
        headers['Content-Type'] = 'application/json; charset=utf-8'

        # Construct and send request
        request = self._client.get(url, query)
        response = self._client.send(request, headers)

        if response.status_code not in [200]:
            raise ErrorException(self._deserialize, response)

        deserialized = None

        if response.status_code == 200:
            deserialized = self._deserialize('DictionaryWrapper', response)

        if raw:
            return deserialized, response

        return deserialized

    @ServiceClient.async_request
    def put_empty(self, complex_body, custom_headers = {}, raw = False, callback = None):
        """

        Put complex types with dictionary property which is empty
        """

        # Construct URL
        url = '/complex/dictionary/typed/empty'

        # Construct parameters
        query = {}

        # Construct headers
        headers = {}
        headers.update(custom_headers)
        headers['Content-Type'] = 'application/json; charset=utf-8'

        # Construct body
        content = self._serialize(complex_body, 'DictionaryWrapper')

        # Construct and send request
        request = self._client.put(url, query)
        response = self._client.send(request, headers, content)

        if response.status_code not in [200]:
            raise ErrorException(self._deserialize, response)

        if raw:
            return None, response

    @ServiceClient.async_request
    def get_null(self, custom_headers = {}, raw = False, callback = None):
        """

        Get complex types with dictionary property which is null
        """

        # Construct URL
        url = '/complex/dictionary/typed/null'

        # Construct parameters
        query = {}

        # Construct headers
        headers = {}
        headers.update(custom_headers)
        headers['Content-Type'] = 'application/json; charset=utf-8'

        # Construct and send request
        request = self._client.get(url, query)
        response = self._client.send(request, headers)

        if response.status_code not in [200]:
            raise ErrorException(self._deserialize, response)

        deserialized = None

        if response.status_code == 200:
            deserialized = self._deserialize('DictionaryWrapper', response)

        if raw:
            return deserialized, response

        return deserialized

    @ServiceClient.async_request
    def get_not_provided(self, custom_headers = {}, raw = False, callback = None):
        """

        Get complex types with dictionary property while server doesn't
        provide a response payload
        """

        # Construct URL
        url = '/complex/dictionary/typed/notprovided'

        # Construct parameters
        query = {}

        # Construct headers
        headers = {}
        headers.update(custom_headers)
        headers['Content-Type'] = 'application/json; charset=utf-8'

        # Construct and send request
        request = self._client.get(url, query)
        response = self._client.send(request, headers)

        if response.status_code not in [200]:
            raise ErrorException(self._deserialize, response)

        deserialized = None

        if response.status_code == 200:
            deserialized = self._deserialize('DictionaryWrapper', response)

        if raw:
            return deserialized, response

        return deserialized
