source 'https://rubygems.org'

# Specify your gem's dependencies in ms_rest.gemspec
gemspec

group :development, :local, :test do
  gem 'rspec'
  gem 'json'
  gem 'timeliness'
  gem 'concurrent-ruby-ext'
  gem 'faraday'
  gem 'faraday-cookie_jar'
end
