# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - master

pool:
  vmImage: "ubuntu-latest"

steps:
  - template: ./build.yaml
    parameters:
      setVersion: true

  - script: npx @microsoft/rush publish --publish --pack --include-all
    displayName: Pack packages

  - script: |
      #  publish the packages (tag as preview by default)
      echo "//registry.npmjs.org/:_authToken=$(azure-sdk-npm-token)" > ./.npmrc 
      rush publish --apply --include-all --set-access-level public
    displayName: Publish packages
    
    #   # publish the packages (tag as preview by default)
    #   echo "//registry.npmjs.org/:_authToken=$(azure-sdk-npm-token)" > ./.npmrc 
    #   for file in common/temp/artifacts/packages/*.tgz 
    #   do
    #     echo "Trying to publish $file:"
    #     npm publish $file --tag latest --access public --no-git-checks || echo no-worries 
    #   done
    # displayName: Publish packages
