# Template for building projects
steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "22.x"
    displayName: "Install Node.js"

  - script: |
      npm install -g npm@6 # Seems to be an with npm 7 and publishing https://github.com/npm/cli/issues/2624.
      npx @microsoft/rush install
    displayName: "Install dependencies"

  - script: |
      npx @microsoft/rush rebuild
    displayName: "Build"
