# Template for building projects
steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "14.x"
    displayName: "Install Node.js"

  - script: |
      npm install -g npm@7.4
      npx @microsoft/rush install
    displayName: "Install dependencies"

  - script: |
      npx @microsoft/rush rebuild
    displayName: "Build"
