---
pipeline-emitter:
  pluginName: pipeline-emitter
  configScope:
    - scope-pipeline-emitter
  inputs: []
swagger-document-override/md-override-loader:
  pluginName: md-override-loader
  configScope: []
  inputs: []
swagger-document/loader:
  pluginName: loader
  configScope: []
  inputs: []
swagger-document/individual/transform:
  pluginName: transform
  configScope: []
  inputs:
    - swagger-document/loader
swagger-document/individual/identity:
  pluginName: identity
  configScope: []
  inputs:
    - swagger-document/individual/transform
swagger-document/compose:
  pluginName: compose
  configScope: []
  inputs:
    - swagger-document/individual/identity
swagger-document/transform-immediate:
  pluginName: transform-immediate
  configScope: []
  inputs:
    - swagger-document-override/md-override-loader
    - swagger-document/compose
swagger-document/transform:
  pluginName: transform
  configScope: []
  inputs:
    - swagger-document/transform-immediate
swagger-document/identity:
  pluginName: identity
  configScope: []
  inputs:
    - swagger-document/transform
swagger-document/emitter:
  pluginName: emitter
  configScope:
    - scope-swagger-document/emitter
  inputs:
    - swagger-document/transform
swagger-document/azure-validator:
  pluginName: azure-validator
  configScope:
    - azure-validator-composed
  inputs:
    - swagger-document/identity
swagger-document/azure-openapi-validator:
  pluginName: azure-openapi-validator
  configScope:
    - azure-validator-composed
  inputs:
    - swagger-document/identity
    - swagger-document/azure-validator
swagger-document/individual/azure-validator:
  pluginName: azure-validator
  configScope:
    - azure-validator-individual
  inputs:
    - swagger-document/individual/identity
swagger-document/individual/azure-openapi-validator:
  pluginName: azure-openapi-validator
  configScope:
    - azure-validator-individual
  inputs:
    - swagger-document/identity
    - swagger-document/individual/azure-validator
csharp/modeler:
  pluginName: modeler
  configScope:
    - csharp
  inputs:
    - swagger-document/identity
csharp/commonmarker:
  pluginName: commonmarker
  configScope:
    - csharp
  inputs:
    - csharp/modeler
csharp/cm/transform:
  pluginName: transform
  configScope:
    - csharp
  inputs:
    - csharp/commonmarker
csharp/cm/emitter:
  pluginName: emitter
  configScope:
    - csharp
    - scope-cm/emitter
  inputs:
    - csharp/cm/transform
csharp/generate:
  pluginName: csharp
  configScope:
    - csharp
  inputs:
    - swagger-document/identity
    - csharp/cm/transform
csharp/simplifier:
  pluginName: csharp-simplifier
  configScope:
    - csharp
  inputs:
    - csharp/generate
csharp/transform:
  pluginName: transform
  configScope:
    - csharp
  inputs:
    - csharp/simplifier
csharp/emitter:
  pluginName: emitter
  configScope:
    - csharp
    - scope-csharp/emitter
  inputs:
    - csharp/transform
